name: core Package Workflow (disabled)

# This file was created by mistake and is intentionally disabled to avoid duplicate triggers.
# Keeping only manual dispatch to prevent automatic runs.

on:
  workflow_dispatch:

jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow is disabled. Use package-core.yml instead."
